language: csharp
solution: ShareX.sln

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - nuget restore ShareX.sln

script:
  - xbuild /p:Configuration=Release ShareX.sln

notifications:
#  irc:
#    channels:
#      - "irc.freenode.net#sharex"
    on_success: always
    on_failure: always
#    skip_join: true